language: java
sudo: true
os:
- linux
jdk:
- openjdk11
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  # COVERITY_SCAN_TOKEN=...
  - secure: nBb8CI0EjNrMLEMEYz6+dnZK7bNA8CmgJAQPKhwasjeCMCe8GXolU54l79om6rPs0r5YtXrgVX5+2YZgJ7E996cBjkBJbXgZ4hj+hhEqJzxrLnBqNc47Q4EAZYsBmXGt40ctP5vYI60JvGzs8wesNEzcjeTyWMkinhwkFxPGOWs=
  # OSS SONATYPE, CI_DEPLOY_USERNAME=...
  - secure: hGeJ+dPc3AI/lOLIuVPuuo1LRrm432NXTsybYvlxIiRUpTDezHLWp/8okg+e+xF93jQSwzrTV0xBuH6upnixzzRzo/6fepT6OINe6a/W/VyQL7vUqOvypHWahU7a85sypEMZ7xSKohrixIIxx+NHjD61Q1s5kSc/r+yGkbU2pzI=
  # OSS SONATYPE, CI_DEPLOY_PASSWORD=...
  - secure: bcwHH/i43WCwnHb6C3G3hNgcS/OOVgCVxoXSUPtsYWcLZxb4cV05vUzs5VO/Iiw/YBRHEQM342yCKS46wunqv2wwEXpzWRTJG0Pwpn2tEj4fjp0OzPsiTx9AWYSkbiQjHoIGWC57LgxNzpuqHJsi4xnc9iiwQaV6mdlJP3Ofb7E=
  # COVERITY_PROJECT_TOKEN=
  - secure: mGSoZXHuppx4dFkpUZkv/0q46/Rh5wleKrqchXpBSEKaWcYEl0FhGCAZz+yCgoqnbu/oqZ5mdwtOdqrBNIdzKfpXSjvReHJijGTMUNHpn1j06nYY+ar5OFDBZcmublf7S93aG0LzxLzqvDvmUKxBiOsFgKr3A/NPJwhB21dYDSE=
  matrix:
  - GROUP=1s
  - GROUP=10s
  - GROUP=ibex
  - GROUP=checker
before_install:
- "/bin/sh ./.travis/install-ibex.sh"
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
- sudo apt-get install jq
# to be adapted to new versions of codacy
- curl https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.0/codacy-coverage-reporter-6.0.0-assembly.jar -o codacy-coverage-reporter-assembly.jar
# - wget -O ~/.codacy/reporter/codacy-reporter-latest.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/2.0.2/codacy-coverage-reporter-2.0.2-assembly.jar
install:
- npm install travis-ping
branches:
  only:
  - "/^develop.*$/"
  - master
  - "/^feature.*$/"
  - coverity_scan
  - modules
notifications:
  email:
    recipients:
    - charles.prudhomme@imt-atlantique.fr
    on_success: always
    on_failure: always
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/26147fbe9b86b606f67d
    on_success: always
    on_failure: always
    on_start: never
before_script:
- mvn validate -Dibex.path=${TRAVIS_BUILD_DIR}/ibex/plugins/java
script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then export LD_LIBRARY_PATH=/usr/local/lib
  && mvn clean install -DtestFailureIgnore=true -Dgroups=$GROUP; fi
addons:
  coverity_scan:
    project:
      name: chocoteam/choco-solver
      description: Build submitted via Travis CI
    notification_email: choco@emn.fr
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity_scan
    condition: "$GROUP = 1s"
after_success:
- bash <(curl -s https://codecov.io/bash)
- travis-ping chocoteam/choco-parsers --branch master --token ${GH_TOKEN}
- java -jar ~/codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

before_deploy:
- echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
- echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
deploy:
- provider: script
  script: "/bin/sh ./.travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: chocoteam/choco-solver
    branch: master
    jdk: oraclejdk8
    condition: "$GROUP = 10s"
- provider: script
  script: "/bin/sh ./.travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: chocoteam/choco-solver
    tags: true
    jdk: oraclejdk8
    condition: "$GROUP = 10s"
