language: java
sudo: true
os:
- linux
jdk:
- oraclejdk8
env:
  global:
  # TEST R
  - secure: hb7XCxuEw3VDF5goORctgcFDwg2Z/WAz1ZHKWNRZmR+M1nN6rgDmwOaJpxepLlU0r/Ku14xspE0yn0nK3P1DFNptXhruDJ1h0+mcwiHdsHOM/Vdo247pPbI9pJTD6gQpNnlgVXAI0s5lkNf3IY2jszzhapKFEMHvnPMFXw/sVzU=
  - secure: LQcrlV3dVHoI2gKGOcDUdLzk32L83SuIK7mN3zNoaWmIh60Q5G1LLsoeEuR0VueY22aNnoOGTI0KmQsTD4JlpebjxWMYpH9SdHTCsge60/fhcv2GhuJwBVD70+Vex7lOKbpuFRQM+JWuyHh8EjWBkjTNYWae1XGzUYBhaJBpgJQ=
   # COVERITY_SCAN_TOKEN
  - secure: SOqRgXwXEaxXYP+zY1C7qIhm09n1Cds4c1yc9TPzokftl8pZKZIbY0bkNl4/HAbDgX0pibrja6nxQ9A1BOuAiCB3mSK7qBPxccq6tvFBhuy2IMxIYFw0tFuP3Cr+NULeYERlLs8wG0oayR8NbdQfYZgFh5+Jzzna133C+X+c/pE=
  # OSS SONATYPE
  - secure: Vh8pphEPAn9q4SvsgN4hldOC3FS0RyTuSpF1b4XhieI8lULNqhXqzH1p/g3yEvh2sbLFWxvBnlAmnFsj3JR7rc+AUewIL2Gse2PYfGlun092nhMGLrOAdbcLHxnauO2WDrdfPzjsTrrXk2DlZZxuUAmdovYFkBswxscezB330P8=
  - secure: UrR8M82bbiqdQEzj6DsK9MXhKN2jVjZQSl9UzBIAqvsxKn2VXlaYlkRJc7AwyfJKHIrriqNtZLrFZFc9maqfj8EDtGaN/Jj2oQ0kAtssHAWDid0oOaWJJn6zoGHKyf02NkO28SjXb99tvC2NE5bpWyIISlEyOKqM2mHJu/14e5M=
  matrix:
  - GROUP=1s
  - GROUP=10s
before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
install:
- npm install travis-ping
branches:
  only:
  - /^develop.*$/
  - master
  - /^feature.*$/
  - coverity_scan
notifications:
  email:
    recipients:
    - choco@emn.fr
    on_success: always
    on_failure: always
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/26147fbe9b86b606f67d
    on_success: change
    on_failure: always
    on_start: never
script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mvn clean install -DtestFailureIgnore=true -Dgroups=$GROUP ; fi
addons:
  coverity_scan:
    project:
      name: "chocoteam/choco-solver"
      description: "Build submitted via Travis CI"
    notification_email: choco@emn.fr
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
after_success:
- bash <(curl -s https://codecov.io/bash)
- travis-ping chocoteam/choco-parsers --branch develop --token ${GH_TOKEN}

before_deploy:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
deploy:
  -
    provider: script
    script: /bin/sh ./.travis/deploy.sh
    skip_cleanup: true
    on:
      repo: chocoteam/choco-solver
      branch: master
      jdk: oraclejdk8
      condition: $GROUP = 10s
  -
    provider: script
    script: /bin/sh ./.travis/deploy.sh
    skip_cleanup: true
    on:
      repo: chocoteam/choco-solver
      tags: true
      jdk: oraclejdk8
      condition: $GROUP = 10s

####
# based on: https://dracoblue.net/dev/uploading-snapshots-and-releases-to-maven-central-with-travis/
####